### PR TITLE
Fixing PE-D bugs

### LINKED ISSUE #139: [PE-D][Tester E] Valid Command with Empty Parameters
Typing the command 

> log

 would throw an exception and kick me out of the program.

Same for 

> show

 

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: sweijie24/ped#1

### LINKED ISSUE #141: [PE-D][Tester E] No Error Handling on Empty Field
Exception thrown if number of servings field is empty when logging.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: sweijie24/ped#2

### LINKED ISSUE #145: [PE-D][Tester E] Improper Handling of Empty Food Item
Able to add servings of an empty food item.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: sweijie24/ped#4

### LINKED ISSUE #146: [PE-D][Tester E] Improper Error Handling for Empty Water Field
Exception thrown when logging empty water field.

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: sweijie24/ped#5

### LINKED ISSUE #148: [PE-D][Tester B] Exception handling - Empty Input for "show"
Upon inputting "show" but without any valid input, exception statement is thrown and exit.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: HikoHikoHiko/ped#2

### LINKED ISSUE #149: [PE-D][Tester E] Improper Error Handling for Empty Duration Field
Exception thrown if duration field is empty.

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: sweijie24/ped#7

### LINKED ISSUE #153: [PE-D][Tester E] Improper Handling for Empty Exercise Field
Able to add empty exercise.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: sweijie24/ped#9

### LINKED ISSUE #156: [PE-D][Tester D] Giving invalid parameters would not result in an error message for log
-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: dtaywd/ped#4

### LINKED ISSUE #170: [PE-D][Tester D] typing log alone crashes the program
-------------
Labels: `severity.High` `type.FeatureFlaw`
original: dtaywd/ped#10

### LINKED ISSUE #171: [PE-D][Tester B] Functionality bug - "log" with invalid input
Program crash upon  inputting "log" only. Exception message is thrown and program stopped.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: HikoHikoHiko/ped#6

### LINKED ISSUE #172: [PE-D][Tester D] leaving the paramter empty for log also crashes the program
-------------
Labels: `severity.High` `type.FeatureFlaw`
original: dtaywd/ped#11

### PR DESCRIPTION
**Pull request by nikhil-2101**
closes #139 
closes #141
closes #146
closes #145
closes #148
closes #149
closes #153
closes #156
closes #171
closes #172
closes #170

### CODE REVIEW

File: src/main/java/activeedge/parser/Parser.java [hunk 1]
```diff
@@ -31,13 +31,32 @@ public void handleInput(String input) {
...
                 String[] items = parts.split("/");
+                if (!items[0].equals("w") && !items[0].equals("m") && !items[0].equals("e")) {
+                    System.out.println("Invalid command. Please enter a valid 'log' command.");
+                    return;
+                }
                 if (items[0].equals("w")) {
-                    String quantityString = items[1];
-                    LogWaterCommand logWaterCommand = new LogWaterCommand(quantityString, currentDateTime);
-                    logWaterCommand.execute();
+                    if(items.length < 2 || items[1].isEmpty()){
```
Comment (alvinnnnnnnnnn) [inline src/main/java/activeedge/parser/Parser.java:51]: good job on this!

**Review by alvinnnnnnnnnn — APPROVED** [review]
